src/ja_lancei/config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get "/welcome_po", to: "welcome_po#index"

  get "/welcome_collaborator", to: "welcome_collaborator#index"

  get '/managers', to: 'managers#new'

  get "/welcome", to: "welcome#index"

  resources :managers, only: [:new, :create]
end

src/ja_lancei/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/ja_lancei/app/models/manager.rb
class Manager < ApplicationRecord
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    validates :password_confirmation, presence: true, length: {minimum: 6}
end

src/ja_lancei/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/ja_lancei/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
    def new
        @manager = Manager.new
    end
     
    def create
        @manager = Manager.new(manager_params)
        
        if @manager.save
            flash[:success] = t("success_manager_create")
            redirect_to welcome_po_path
        else
            render 'new'
        end
    end

    private
        def manager_params
            params.require(:manager).permit(:email, :first_name, :last_name, :password, :password_confirmation)
        end
end

src/ja_lancei/app/controllers/welcome_collaborator_controller.rb
class WelcomeCollaboratorController < ApplicationController
end

src/ja_lancei/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

src/ja_lancei/app/controllers/welcome_po_controller.rb
class WelcomePoController < ApplicationController
end

src/ja_lancei/app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

src/ja_lancei/app/helpers/managers_helper.rb
module ManagersHelper
end

src/ja_lancei/app/helpers/welcome_collaborator_helper.rb
module WelcomeCollaboratorHelper
end

src/ja_lancei/app/helpers/welcome_helper.rb
module WelcomeHelper
end

src/ja_lancei/app/helpers/welcome_po_helper.rb
module WelcomePoHelper
end

src/ja_lancei/app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class="alert alert-danger">
            <%= t('error_ops_expression') %> <%= pluralize(object.errors.count, 'erro', 'erros') %>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

src/ja_lancei/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg" id="header-navbar">
    <a class="navbar-brand" href="#">Já Lancei</a>

    <div class="collapse navbar-collapse">
        
    </div>
</nav>

src/ja_lancei/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>JaLancei</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<%= message %>
				<% end %>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

src/ja_lancei/app/views/managers/new.html.erb
<%= form_for @manager, html: {class: "padding-elemento-topo-pagina", id: "manager-form"} do |f| %>
    <%= render 'layouts/error_messages', object: f.object %>
    
    <fieldset>
        <div class="form-group">
            <div class="row align-items-center text-center">
                <legend><%= t("manager_legend") %></legend>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-2 offset-md-2 col-xs-12">
                    <%= f.label :email, class: "control-label align-middle no-margin-bottom" %>
                </div>
                <div class="col-md-6 col-xs-12">
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-2 offset-md-2 col-xs-12">
                    <%= f.label :first_name, class: "control-label align-middle no-margin-bottom" %>
                </div>
                <div class="col-md-6 col-xs-12">
                    <%= f.text_field :first_name, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-2 offset-md-2 col-xs-12">
                    <%= f.label :last_name, class: "control-label align-middle no-margin-bottom" %>
                </div>
                <div class="col-md-6 col-xs-12">
                    <%= f.text_field :last_name, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-2 offset-md-2 col-xs-12">
                    <%= f.label :password, class: "control-label align-middle no-margin-bottom" %>
                </div>
                <div class="col-md-6 col-xs-12">
                    <%= f.password_field :password, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-2 offset-md-2 col-xs-12">
                    <%= f.label :password_confirmation, class: "control-label align-middle no-margin-bottom" %>
                </div>
                <div class="col-md-6 col-xs-12">
                    <%= f.password_field :password_confirmation, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-12 col-xs-12 text-center">
                    <%= f.submit t("manager_submit"), class: 'btn btn-secondary' %>
                </div>
            </div>
        </div>
    </fieldset>

<% end %>

src/ja_lancei/app/views/welcome/index.html.erb
<div class="row">
    <div class="col-md-12 col-xs-12 div-titulo-pagina padding-elemento-topo-pagina">
        <p><%= t('text_welcome') %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to t('button_po'), welcome_po_path, method: "get", class: 'btn btn-success button-po-collaborator' %>
    </div>
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to t('button_collaborator'), welcome_collaborator_path, method: "get", class: 'btn btn-success button-po-collaborator button-collaborator' %>            
    </div>
</div>

src/ja_lancei/app/views/welcome_collaborator/index.html.erb
<div class="row">
    <div class="col-md-12 col-xs-12 padding-elemento-topo-pagina div-titulo-pagina">
        <p class="titulo-pagina" id="titulo-pagina-welcome-collaborator"><%= t("legend_session_collaborator") %></p>
    </div>
</div>
<div class="row text-center">
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to 'Crie sua conta', "#", method: "get", action: "create", class: 'btn btn-success button-po-collaborator' %>
    </div>
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to 'Faça login', "#", method: "#", action: "#", class: 'btn btn-success button-po-collaborator button-collaborator' %>
    </div>
</div>

src/ja_lancei/app/views/welcome_po/index.html.erb
<div class="row">
    <div class="col-md-12 col-xs-12 padding-elemento-topo-pagina div-titulo-pagina">
        <p class="titulo-pagina" id="titulo-pagina-welcome-po"><%= t("legend_session_po") %></p>
    </div>
</div>
<div class="row text-center">
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to 'Crie sua conta', new_manager_path, method: "get", action: "create", class: 'btn btn-success button-po-collaborator' %>
    </div>
    <div class="col-md-6 col-xs-12 div-button-po-collaborator">
        <%= button_to 'Faça login', "#", method: "#", action: "#", class: 'btn btn-success button-po-collaborator button-collaborator' %>
    </div>
</div>